spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=sA/5xpndGAMozFcjszCXulKN+CgUGt0Oih4QqeCJ7AY=
jwt.expiration=86400000

server.port=8080

# 1. Increase Multipart limits (just in case you use File upload later)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 2. Increase Tomcat's internal form/post limit (CRITICAL for Base64)
server.tomcat.max-http-form-post-size=10MB
server.tomcat.max-swallow-size=10MB

# 3. Increase the memory buffer for JSON parsing (Spring 3.x specific)
spring.codec.max-in-memory-size=10MB

# 4. Ensure Jackson doesn't fail on large strings
spring.jackson.serialization.fail-on-empty-beans=false




# check the DB using ( SELECT id, name, email, mobile, role, LENGTH(profile_image) AS img_size FROM users;)